// Code generated by pigeon; DO NOT EDIT.

package main

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

var groupStack Stack[Component] = newStack[Component]()
var documentBuilder IDocumentBuilder = newDocumentBuilder()
var argumentStack Stack[string] = newStack[string]()

var g = &grammar{
	rules: []*rule{
		{
			name: "Input",
			pos:  position{line: 15, col: 1, offset: 556},
			expr: &actionExpr{
				pos: position{line: 15, col: 10, offset: 565},
				run: (*parser).callonInput1,
				expr: &seqExpr{
					pos: position{line: 15, col: 10, offset: 565},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 15, col: 10, offset: 565},
							name: "text",
						},
						&labeledExpr{
							pos:   position{line: 15, col: 15, offset: 570},
							label: "prerequisite",
							expr: &ruleRefExpr{
								pos:  position{line: 15, col: 28, offset: 583},
								name: "PrerequisiteContent",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 15, col: 48, offset: 603},
							name: "text",
						},
						&labeledExpr{
							pos:   position{line: 15, col: 53, offset: 608},
							label: "docclass",
							expr: &ruleRefExpr{
								pos:  position{line: 15, col: 62, offset: 617},
								name: "DocumentClass",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 15, col: 76, offset: 631},
							name: "text",
						},
						&labeledExpr{
							pos:   position{line: 15, col: 81, offset: 636},
							label: "preamble",
							expr: &ruleRefExpr{
								pos:  position{line: 15, col: 90, offset: 645},
								name: "Preamble",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 15, col: 99, offset: 654},
							name: "text",
						},
						&labeledExpr{
							pos:   position{line: 15, col: 104, offset: 659},
							label: "content",
							expr: &ruleRefExpr{
								pos:  position{line: 15, col: 112, offset: 667},
								name: "DocumentContent",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 15, col: 128, offset: 683},
							name: "text",
						},
						&ruleRefExpr{
							pos:  position{line: 15, col: 133, offset: 688},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "PrerequisiteContent",
			pos:  position{line: 77, col: 1, offset: 2667},
			expr: &actionExpr{
				pos: position{line: 77, col: 24, offset: 2690},
				run: (*parser).callonPrerequisiteContent1,
				expr: &labeledExpr{
					pos:   position{line: 77, col: 24, offset: 2690},
					label: "lines",
					expr: &ruleRefExpr{
						pos:  position{line: 77, col: 30, offset: 2696},
						name: "MultiLaTeXLines",
					},
				},
			},
		},
		{
			name: "DocumentClass",
			pos:  position{line: 82, col: 1, offset: 2824},
			expr: &choiceExpr{
				pos: position{line: 82, col: 18, offset: 2841},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 82, col: 18, offset: 2841},
						run: (*parser).callonDocumentClass2,
						expr: &seqExpr{
							pos: position{line: 82, col: 18, offset: 2841},
							exprs: []any{
								&ruleRefExpr{
									pos:  position{line: 82, col: 18, offset: 2841},
									name: "command_start",
								},
								&labeledExpr{
									pos:   position{line: 82, col: 32, offset: 2855},
									label: "name",
									expr: &litMatcher{
										pos:        position{line: 82, col: 37, offset: 2860},
										val:        "documentclass",
										ignoreCase: false,
										want:       "\"documentclass\"",
									},
								},
								&labeledExpr{
									pos:   position{line: 82, col: 53, offset: 2876},
									label: "args",
									expr: &ruleRefExpr{
										pos:  position{line: 82, col: 58, offset: 2881},
										name: "MultiArgument",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 87, col: 5, offset: 3034},
						run: (*parser).callonDocumentClass9,
						expr: &labeledExpr{
							pos:   position{line: 87, col: 5, offset: 3034},
							label: "t",
							expr: &ruleRefExpr{
								pos:  position{line: 87, col: 7, offset: 3036},
								name: "text",
							},
						},
					},
				},
			},
		},
		{
			name: "Preamble",
			pos:  position{line: 96, col: 1, offset: 3322},
			expr: &actionExpr{
				pos: position{line: 96, col: 13, offset: 3334},
				run: (*parser).callonPreamble1,
				expr: &labeledExpr{
					pos:   position{line: 96, col: 13, offset: 3334},
					label: "lines",
					expr: &ruleRefExpr{
						pos:  position{line: 96, col: 19, offset: 3340},
						name: "MultiSimpleLaTeXLines",
					},
				},
			},
		},
		{
			name: "DocumentContent",
			pos:  position{line: 101, col: 1, offset: 3463},
			expr: &actionExpr{
				pos: position{line: 101, col: 20, offset: 3482},
				run: (*parser).callonDocumentContent1,
				expr: &labeledExpr{
					pos:   position{line: 101, col: 20, offset: 3482},
					label: "lines",
					expr: &ruleRefExpr{
						pos:  position{line: 101, col: 26, offset: 3488},
						name: "MultiLaTeXLines",
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 107, col: 1, offset: 3640},
			expr: &notExpr{
				pos: position{line: 107, col: 8, offset: 3647},
				expr: &anyMatcher{
					line: 107, col: 9, offset: 3648,
				},
			},
		},
		{
			name: "MultiLaTeXLines",
			pos:  position{line: 113, col: 1, offset: 3813},
			expr: &actionExpr{
				pos: position{line: 113, col: 20, offset: 3832},
				run: (*parser).callonMultiLaTeXLines1,
				expr: &labeledExpr{
					pos:   position{line: 113, col: 20, offset: 3832},
					label: "lines",
					expr: &zeroOrMoreExpr{
						pos: position{line: 113, col: 26, offset: 3838},
						expr: &ruleRefExpr{
							pos:  position{line: 113, col: 26, offset: 3838},
							name: "LaTeXLine",
						},
					},
				},
			},
		},
		{
			name: "LaTeXLine",
			pos:  position{line: 168, col: 1, offset: 5552},
			expr: &actionExpr{
				pos: position{line: 168, col: 14, offset: 5565},
				run: (*parser).callonLaTeXLine1,
				expr: &seqExpr{
					pos: position{line: 168, col: 14, offset: 5565},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 168, col: 14, offset: 5565},
							name: "text",
						},
						&labeledExpr{
							pos:   position{line: 168, col: 19, offset: 5570},
							label: "line",
							expr: &choiceExpr{
								pos: position{line: 168, col: 25, offset: 5576},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 168, col: 25, offset: 5576},
										name: "BeginGroup",
									},
									&ruleRefExpr{
										pos:  position{line: 168, col: 38, offset: 5589},
										name: "EndGroup",
									},
									&ruleRefExpr{
										pos:  position{line: 168, col: 49, offset: 5600},
										name: "SimpleLaTeXLine",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 168, col: 66, offset: 5617},
							name: "text",
						},
					},
				},
			},
		},
		{
			name: "BeginGroup",
			pos:  position{line: 172, col: 1, offset: 5652},
			expr: &actionExpr{
				pos: position{line: 172, col: 15, offset: 5666},
				run: (*parser).callonBeginGroup1,
				expr: &seqExpr{
					pos: position{line: 172, col: 15, offset: 5666},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 172, col: 15, offset: 5666},
							name: "command_start",
						},
						&litMatcher{
							pos:        position{line: 172, col: 29, offset: 5680},
							val:        "begin",
							ignoreCase: false,
							want:       "\"begin\"",
						},
						&labeledExpr{
							pos:   position{line: 172, col: 37, offset: 5688},
							label: "args",
							expr: &ruleRefExpr{
								pos:  position{line: 172, col: 42, offset: 5693},
								name: "MultiArgument",
							},
						},
					},
				},
			},
		},
		{
			name: "EndGroup",
			pos:  position{line: 201, col: 1, offset: 6459},
			expr: &actionExpr{
				pos: position{line: 201, col: 13, offset: 6471},
				run: (*parser).callonEndGroup1,
				expr: &seqExpr{
					pos: position{line: 201, col: 13, offset: 6471},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 201, col: 13, offset: 6471},
							name: "command_start",
						},
						&litMatcher{
							pos:        position{line: 201, col: 27, offset: 6485},
							val:        "end",
							ignoreCase: false,
							want:       "\"end\"",
						},
						&labeledExpr{
							pos:   position{line: 201, col: 33, offset: 6491},
							label: "args",
							expr: &ruleRefExpr{
								pos:  position{line: 201, col: 38, offset: 6496},
								name: "MultiArgument",
							},
						},
					},
				},
			},
		},
		{
			name: "MultiSimpleLaTeXLines",
			pos:  position{line: 243, col: 1, offset: 7724},
			expr: &actionExpr{
				pos: position{line: 243, col: 26, offset: 7749},
				run: (*parser).callonMultiSimpleLaTeXLines1,
				expr: &labeledExpr{
					pos:   position{line: 243, col: 26, offset: 7749},
					label: "lines",
					expr: &zeroOrMoreExpr{
						pos: position{line: 243, col: 32, offset: 7755},
						expr: &ruleRefExpr{
							pos:  position{line: 243, col: 32, offset: 7755},
							name: "SimpleWrappedLaTeXLine",
						},
					},
				},
			},
		},
		{
			name: "SimpleWrappedLaTeXLine",
			pos:  position{line: 247, col: 1, offset: 7838},
			expr: &actionExpr{
				pos: position{line: 247, col: 27, offset: 7864},
				run: (*parser).callonSimpleWrappedLaTeXLine1,
				expr: &seqExpr{
					pos: position{line: 247, col: 27, offset: 7864},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 247, col: 27, offset: 7864},
							name: "text",
						},
						&labeledExpr{
							pos:   position{line: 247, col: 32, offset: 7869},
							label: "line",
							expr: &ruleRefExpr{
								pos:  position{line: 247, col: 37, offset: 7874},
								name: "SimpleLaTeXLine",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 247, col: 53, offset: 7890},
							name: "text",
						},
					},
				},
			},
		},
		{
			name: "SimpleLaTeXLine",
			pos:  position{line: 253, col: 1, offset: 8098},
			expr: &actionExpr{
				pos: position{line: 253, col: 20, offset: 8117},
				run: (*parser).callonSimpleLaTeXLine1,
				expr: &seqExpr{
					pos: position{line: 253, col: 20, offset: 8117},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 253, col: 20, offset: 8117},
							name: "command_start",
						},
						&notExpr{
							pos: position{line: 253, col: 34, offset: 8131},
							expr: &litMatcher{
								pos:        position{line: 253, col: 35, offset: 8132},
								val:        "documentclass",
								ignoreCase: false,
								want:       "\"documentclass\"",
							},
						},
						&notExpr{
							pos: position{line: 253, col: 51, offset: 8148},
							expr: &litMatcher{
								pos:        position{line: 253, col: 52, offset: 8149},
								val:        "begin",
								ignoreCase: false,
								want:       "\"begin\"",
							},
						},
						&notExpr{
							pos: position{line: 253, col: 60, offset: 8157},
							expr: &litMatcher{
								pos:        position{line: 253, col: 61, offset: 8158},
								val:        "end",
								ignoreCase: false,
								want:       "\"end\"",
							},
						},
						&labeledExpr{
							pos:   position{line: 253, col: 67, offset: 8164},
							label: "name",
							expr: &oneOrMoreExpr{
								pos: position{line: 253, col: 72, offset: 8169},
								expr: &ruleRefExpr{
									pos:  position{line: 253, col: 72, offset: 8169},
									name: "word",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 253, col: 78, offset: 8175},
							label: "args",
							expr: &ruleRefExpr{
								pos:  position{line: 253, col: 83, offset: 8180},
								name: "MultiArgument",
							},
						},
					},
				},
			},
		},
		{
			name: "MultiArgument",
			pos:  position{line: 266, col: 1, offset: 8667},
			expr: &actionExpr{
				pos: position{line: 266, col: 18, offset: 8684},
				run: (*parser).callonMultiArgument1,
				expr: &labeledExpr{
					pos:   position{line: 266, col: 18, offset: 8684},
					label: "arguments",
					expr: &zeroOrMoreExpr{
						pos: position{line: 266, col: 28, offset: 8694},
						expr: &ruleRefExpr{
							pos:  position{line: 266, col: 28, offset: 8694},
							name: "Argument",
						},
					},
				},
			},
		},
		{
			name: "Argument",
			pos:  position{line: 271, col: 1, offset: 8877},
			expr: &actionExpr{
				pos: position{line: 271, col: 13, offset: 8889},
				run: (*parser).callonArgument1,
				expr: &labeledExpr{
					pos:   position{line: 271, col: 13, offset: 8889},
					label: "argument",
					expr: &choiceExpr{
						pos: position{line: 271, col: 23, offset: 8899},
						alternatives: []any{
							&ruleRefExpr{
								pos:  position{line: 271, col: 23, offset: 8899},
								name: "OptionArgument",
							},
							&ruleRefExpr{
								pos:  position{line: 271, col: 40, offset: 8916},
								name: "ClassArgument",
							},
						},
					},
				},
			},
		},
		{
			name: "ClassArgument",
			pos:  position{line: 277, col: 1, offset: 9094},
			expr: &choiceExpr{
				pos: position{line: 277, col: 18, offset: 9111},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 277, col: 18, offset: 9111},
						run: (*parser).callonClassArgument2,
						expr: &seqExpr{
							pos: position{line: 277, col: 18, offset: 9111},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 277, col: 18, offset: 9111},
									val:        "{",
									ignoreCase: false,
									want:       "\"{\"",
								},
								&ruleRefExpr{
									pos:  position{line: 277, col: 22, offset: 9115},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 277, col: 24, offset: 9117},
									label: "class",
									expr: &ruleRefExpr{
										pos:  position{line: 277, col: 30, offset: 9123},
										name: "ArgumentContent",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 277, col: 46, offset: 9139},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 277, col: 48, offset: 9141},
									val:        "}",
									ignoreCase: false,
									want:       "\"}\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 289, col: 5, offset: 9558},
						run: (*parser).callonClassArgument10,
						expr: &seqExpr{
							pos: position{line: 289, col: 5, offset: 9558},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 289, col: 5, offset: 9558},
									val:        "{",
									ignoreCase: false,
									want:       "\"{\"",
								},
								&ruleRefExpr{
									pos:  position{line: 289, col: 9, offset: 9562},
									name: "_",
								},
								&ruleRefExpr{
									pos:  position{line: 289, col: 11, offset: 9564},
									name: "ArgumentContent",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 295, col: 5, offset: 9800},
						run: (*parser).callonClassArgument15,
						expr: &seqExpr{
							pos: position{line: 295, col: 5, offset: 9800},
							exprs: []any{
								&ruleRefExpr{
									pos:  position{line: 295, col: 5, offset: 9800},
									name: "ArgumentContent",
								},
								&ruleRefExpr{
									pos:  position{line: 295, col: 21, offset: 9816},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 295, col: 23, offset: 9818},
									val:        "}",
									ignoreCase: false,
									want:       "\"}\"",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "OptionArgument",
			pos:  position{line: 304, col: 1, offset: 10139},
			expr: &choiceExpr{
				pos: position{line: 304, col: 19, offset: 10157},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 304, col: 19, offset: 10157},
						run: (*parser).callonOptionArgument2,
						expr: &seqExpr{
							pos: position{line: 304, col: 19, offset: 10157},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 304, col: 19, offset: 10157},
									val:        "[",
									ignoreCase: false,
									want:       "\"[\"",
								},
								&ruleRefExpr{
									pos:  position{line: 304, col: 23, offset: 10161},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 304, col: 25, offset: 10163},
									label: "options",
									expr: &ruleRefExpr{
										pos:  position{line: 304, col: 33, offset: 10171},
										name: "ArgumentContent",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 304, col: 49, offset: 10187},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 304, col: 51, offset: 10189},
									val:        "]",
									ignoreCase: false,
									want:       "\"]\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 309, col: 5, offset: 10332},
						run: (*parser).callonOptionArgument10,
						expr: &seqExpr{
							pos: position{line: 309, col: 5, offset: 10332},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 309, col: 5, offset: 10332},
									val:        "[",
									ignoreCase: false,
									want:       "\"[\"",
								},
								&ruleRefExpr{
									pos:  position{line: 309, col: 9, offset: 10336},
									name: "_",
								},
								&ruleRefExpr{
									pos:  position{line: 309, col: 11, offset: 10338},
									name: "ArgumentContent",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 315, col: 5, offset: 10576},
						run: (*parser).callonOptionArgument15,
						expr: &seqExpr{
							pos: position{line: 315, col: 5, offset: 10576},
							exprs: []any{
								&ruleRefExpr{
									pos:  position{line: 315, col: 5, offset: 10576},
									name: "ArgumentContent",
								},
								&ruleRefExpr{
									pos:  position{line: 315, col: 21, offset: 10592},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 315, col: 23, offset: 10594},
									val:        "]",
									ignoreCase: false,
									want:       "\"]\"",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ArgumentContent",
			pos:  position{line: 328, col: 1, offset: 11042},
			expr: &actionExpr{
				pos: position{line: 328, col: 20, offset: 11061},
				run: (*parser).callonArgumentContent1,
				expr: &oneOrMoreExpr{
					pos: position{line: 328, col: 20, offset: 11061},
					expr: &ruleRefExpr{
						pos:  position{line: 328, col: 20, offset: 11061},
						name: "ArgumentPart",
					},
				},
			},
		},
		{
			name: "ArgumentPart",
			pos:  position{line: 333, col: 1, offset: 11239},
			expr: &choiceExpr{
				pos: position{line: 333, col: 17, offset: 11255},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 333, col: 17, offset: 11255},
						name: "SimpleLaTeXLine",
					},
					&ruleRefExpr{
						pos:  position{line: 333, col: 35, offset: 11273},
						name: "non_argument_content",
					},
					&ruleRefExpr{
						pos:  position{line: 333, col: 58, offset: 11296},
						name: "ArgumentOpen",
					},
					&ruleRefExpr{
						pos:  position{line: 333, col: 73, offset: 11311},
						name: "ArgumentClose",
					},
				},
			},
		},
		{
			name: "ArgumentOpen",
			pos:  position{line: 336, col: 1, offset: 11382},
			expr: &actionExpr{
				pos: position{line: 336, col: 17, offset: 11398},
				run: (*parser).callonArgumentOpen1,
				expr: &labeledExpr{
					pos:   position{line: 336, col: 17, offset: 11398},
					label: "str",
					expr: &ruleRefExpr{
						pos:  position{line: 336, col: 21, offset: 11402},
						name: "argument_opener",
					},
				},
			},
		},
		{
			name: "ArgumentClose",
			pos:  position{line: 342, col: 1, offset: 11509},
			expr: &actionExpr{
				pos: position{line: 342, col: 18, offset: 11526},
				run: (*parser).callonArgumentClose1,
				expr: &seqExpr{
					pos: position{line: 342, col: 18, offset: 11526},
					exprs: []any{
						&andCodeExpr{
							pos: position{line: 342, col: 18, offset: 11526},
							run: (*parser).callonArgumentClose3,
						},
						&labeledExpr{
							pos:   position{line: 349, col: 3, offset: 11796},
							label: "str",
							expr: &ruleRefExpr{
								pos:  position{line: 349, col: 7, offset: 11800},
								name: "argument_closer",
							},
						},
					},
				},
			},
		},
		{
			name: "argument_opener",
			pos:  position{line: 380, col: 1, offset: 12689},
			expr: &charClassMatcher{
				pos:        position{line: 380, col: 20, offset: 12708},
				val:        "[{[]",
				chars:      []rune{'{', '['},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "argument_closer",
			pos:  position{line: 381, col: 1, offset: 12714},
			expr: &charClassMatcher{
				pos:        position{line: 381, col: 20, offset: 12733},
				val:        "[}\\]]",
				chars:      []rune{'}', ']'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "non_argument_content",
			pos:  position{line: 382, col: 1, offset: 12740},
			expr: &charClassMatcher{
				pos:        position{line: 382, col: 25, offset: 12764},
				val:        "[^\\\\{[\\]}]",
				chars:      []rune{'\\', '{', '[', ']', '}'},
				ignoreCase: false,
				inverted:   true,
			},
		},
		{
			name: "command_start",
			pos:  position{line: 385, col: 1, offset: 12837},
			expr: &litMatcher{
				pos:        position{line: 385, col: 18, offset: 12854},
				val:        "\\",
				ignoreCase: false,
				want:       "\"\\\\\"",
			},
		},
		{
			name: "non_special",
			pos:  position{line: 386, col: 1, offset: 12860},
			expr: &charClassMatcher{
				pos:        position{line: 386, col: 16, offset: 12875},
				val:        "[^\\\\]",
				chars:      []rune{'\\'},
				ignoreCase: false,
				inverted:   true,
			},
		},
		{
			name:        "text",
			displayName: "\"zero or more non-special characters\"",
			pos:         position{line: 387, col: 1, offset: 12882},
			expr: &zeroOrMoreExpr{
				pos: position{line: 387, col: 47, offset: 12928},
				expr: &ruleRefExpr{
					pos:  position{line: 387, col: 47, offset: 12928},
					name: "non_special",
				},
			},
		},
		{
			name: "word",
			pos:  position{line: 390, col: 1, offset: 12972},
			expr: &charClassMatcher{
				pos:        position{line: 390, col: 9, offset: 12980},
				val:        "[a-zA-Z0-9_]",
				chars:      []rune{'_'},
				ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "non_word",
			pos:  position{line: 391, col: 1, offset: 12994},
			expr: &charClassMatcher{
				pos:        position{line: 391, col: 13, offset: 13006},
				val:        "[^a-zA-Z0-9_]",
				chars:      []rune{'_'},
				ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
				ignoreCase: false,
				inverted:   true,
			},
		},
		{
			name: "non_whitespace",
			pos:  position{line: 394, col: 1, offset: 13047},
			expr: &charClassMatcher{
				pos:        position{line: 394, col: 19, offset: 13065},
				val:        "[^ \\n\\t\\r]",
				chars:      []rune{' ', '\n', '\t', '\r'},
				ignoreCase: false,
				inverted:   true,
			},
		},
		{
			name: "whitespace",
			pos:  position{line: 395, col: 1, offset: 13077},
			expr: &charClassMatcher{
				pos:        position{line: 395, col: 15, offset: 13091},
				val:        "[ \\n\\t\\r]",
				chars:      []rune{' ', '\n', '\t', '\r'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name:        "_",
			displayName: "\"zero or more whitespace characters\"",
			pos:         position{line: 396, col: 1, offset: 13102},
			expr: &zeroOrMoreExpr{
				pos: position{line: 396, col: 43, offset: 13144},
				expr: &ruleRefExpr{
					pos:  position{line: 396, col: 43, offset: 13144},
					name: "whitespace",
				},
			},
		},
	},
}

func (c *current) onInput1(prerequisite, docclass, preamble, content any) (any, error) {

	// creating coordinates for potential error handling
	startCoord, endCoord, err := GetCoordinates(c.pos.line, c.pos.col, c.text)
	if err != nil {
		return nil, DummyError(err)
	}

	// handling prerequisite
	if prerequisite != nil {
		for _, component := range prerequisite.([]Component) {
			errFn := documentBuilder.addPrerequisiteLine(component)
			if errFn != nil {
				return nil, errFn(*startCoord, *endCoord)
			}
		}
	}

	// handling document class
	if docclass != nil {
		// add to the document
		errFn := documentBuilder.addDocumentClass(*docclass.(*Line))
		if errFn != nil {
			return nil, errFn(*startCoord, *endCoord)
		}
	}

	// handling preamble
	if preamble != nil {
		for _, line := range preamble.([]Line) {
			var component Component = &line
			errFn := documentBuilder.addPreambleLine(component)
			if errFn != nil {
				return nil, errFn(*startCoord, *endCoord)
			}
		}
	}

	// handling document content
	if content != nil {
		for i, component := range content.([]Component) {
			var errFn CreateError
			if i+1 < len(content.([]Component)) {
				errFn = documentBuilder.addPreambleLine(component)
			} else {
				errFn = documentBuilder.addDocumentContent(component)
			}
			if errFn != nil {
				return nil, errFn(*startCoord, *endCoord)
			}
		}
	}

	// additional checks over the document occur during creation
	document, errFn := documentBuilder.buildDocument()
	if errFn != nil {
		return nil, errFn(*startCoord, *endCoord)
	}
	return document, nil
}

func (p *parser) callonInput1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInput1(stack["prerequisite"], stack["docclass"], stack["preamble"], stack["content"])
}

func (c *current) onPrerequisiteContent1(lines any) (any, error) {

	return lines, nil
}

func (p *parser) callonPrerequisiteContent1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPrerequisiteContent1(stack["lines"])
}

func (c *current) onDocumentClass2(name, args any) (any, error) {

	// parse data
	arguments := args.([]Argument)
	line := newLine(string(name.([]byte)), arguments)
	return line, nil
}

func (p *parser) callonDocumentClass2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDocumentClass2(stack["name"], stack["args"])
}

func (c *current) onDocumentClass9(t any) (any, error) {

	startCoord, endCoord, err := GetCoordinates(c.pos.line, c.pos.col, c.text)
	if err != nil {
		return nil, DummyError(err)
	}
	return nil, DOCUMENT_CLASS_NOT_FOUND(*startCoord, *endCoord)
}

func (p *parser) callonDocumentClass9() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDocumentClass9(stack["t"])
}

func (c *current) onPreamble1(lines any) (any, error) {

	return lines, nil
}

func (p *parser) callonPreamble1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPreamble1(stack["lines"])
}

func (c *current) onDocumentContent1(lines any) (any, error) {

	return lines, nil
}

func (p *parser) callonDocumentContent1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDocumentContent1(stack["lines"])
}

func (c *current) onMultiLaTeXLines1(lines any) (any, error) {

	// creating coordinates for potential error handling
	startCoord, endCoord, err := GetCoordinates(c.pos.line, c.pos.col, c.text)
	if err != nil {
		return nil, DummyError(err)
	}

	var result []Component
	stack := newStack[Component]()
	for _, line := range lines.([]any) {
		if line == nil {
			continue
		}

		// Handling ending groups
		_, ok := line.(string)
		if ok {
			_, err := stack.Pop()
			if err != nil {
				return nil, err(*startCoord, *endCoord)
			}
			continue
		}

		// adding component to pre-existing groups if necessary
		component, ok := line.(Component)
		if !ok {
			return nil, SERVER_RESPONSIBLE_NON_COMPONENT_DATA_STRUCTURE(*startCoord, *endCoord)
		}
		if !stack.IsEmpty() {
			peek, err := stack.Peek()
			if err != nil {
				return nil, err(*startCoord, *endCoord)
			}
			peer, ok := peek.(*Group)
			if !ok {
				return nil, SERVER_RESPONSIBLE_STACK_CONTAINS_NON_GROUP_ELEMENT(*startCoord, *endCoord)
			}
			peer.AddComponent(component)

			// add to the result if this is the topmost layer
		} else if component != nil { // nil check is provided for future-proofing, even if it is redundant atm
			result = append(result, component)
		}

		// handling grouped contexts
		_, ok = component.(*Group)
		if ok {
			stack.Push(component)
			continue
		}
	}
	return result, nil
}

func (p *parser) callonMultiLaTeXLines1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMultiLaTeXLines1(stack["lines"])
}

func (c *current) onLaTeXLine1(line any) (any, error) {

	return line, nil
}

func (p *parser) callonLaTeXLine1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLaTeXLine1(stack["line"])
}

func (c *current) onBeginGroup1(args any) (any, error) {

	// retrieving useful data
	startCoord, endCoord, err := GetCoordinates(c.pos.line, c.pos.col, c.text)
	if err != nil {
		return nil, DummyError(err)
	}
	arguments := args.([]Argument)

	// retrieving name of the group
	var name string
	found := false
	for _, arg := range arguments {
		class, ok := arg.(*ClassArgument)
		if ok {
			name = strings.Trim(class.GetValue().(string), WHITESPACE)
			found = true
			break
		}
	}
	if !found {
		return nil, MISSING_BEGIN_GROUP_NAME(*startCoord, *endCoord)
	}

	// handling groups ordering
	group := newGroup(name, arguments)
	groupStack.Push(group)
	return group, nil
}

func (p *parser) callonBeginGroup1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBeginGroup1(stack["args"])
}

func (c *current) onEndGroup1(args any) (any, error) {

	// creating coordinates for potential error handling
	startCoord, endCoord, err := GetCoordinates(c.pos.line, c.pos.col, c.text)
	if err != nil {
		return nil, DummyError(err)
	}
	arguments := args.([]Argument)

	// retrieving name of the group
	var name string
	found := false
	for _, arg := range arguments {
		class, ok := arg.(*ClassArgument)
		if ok {
			name = strings.Trim(class.GetValue().(string), WHITESPACE)
			found = true
			break
		}
	}
	if !found {
		return nil, MISSING_END_GROUP_NAME(*startCoord, *endCoord)
	}

	// checking a begin statement exists
	peek, err := groupStack.Peek()
	if err != nil {
		return nil, GROUP_BEGIN_MISSING(*startCoord, *endCoord)
	}

	// checking the group beginning matches its end
	if peek.GetName() != name {
		return nil, GROUP_NAME_MISMATCH(*startCoord, *endCoord)
	}
	groupStack.Pop()

	// requires a non-nil value to indicate it is not an error
	return "_", nil
}

func (p *parser) callonEndGroup1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEndGroup1(stack["args"])
}

func (c *current) onMultiSimpleLaTeXLines1(lines any) (any, error) {

	return AnyInterfaceToTSlice[Line](lines), nil
}

func (p *parser) callonMultiSimpleLaTeXLines1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMultiSimpleLaTeXLines1(stack["lines"])
}

func (c *current) onSimpleWrappedLaTeXLine1(line any) (any, error) {

	return *line.(*Line), nil
}

func (p *parser) callonSimpleWrappedLaTeXLine1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSimpleWrappedLaTeXLine1(stack["line"])
}

func (c *current) onSimpleLaTeXLine1(name, args any) (any, error) {

	arguments := args.([]Argument)
	line := newLine(AnyInterfaceToString(name), arguments)
	return line, nil
}

func (p *parser) callonSimpleLaTeXLine1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSimpleLaTeXLine1(stack["name"], stack["args"])
}

func (c *current) onMultiArgument1(arguments any) (any, error) {

	return AnyInterfaceToTSlice[Argument](RemoveNilElements(arguments.([]any))), nil
}

func (p *parser) callonMultiArgument1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMultiArgument1(stack["arguments"])
}

func (c *current) onArgument1(argument any) (any, error) {

	argumentStack = newStack[string]()
	return argument, nil
}

func (p *parser) callonArgument1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArgument1(stack["argument"])
}

func (c *current) onClassArgument2(class any) (any, error) {

	startCoord, endCoord, err := GetCoordinates(c.pos.line, c.pos.col, c.text)
	if err != nil {
		return nil, DummyError(err)
	}
	if !argumentStack.IsEmpty() {
		return nil, INNER_ARGUMENT_END_MISSING(*startCoord, *endCoord) // custom err later
	}
	argument := newClassArgument(class.(string))
	return argument, nil

	// Handling if the closing brace '}' is missing
}

func (p *parser) callonClassArgument2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onClassArgument2(stack["class"])
}

func (c *current) onClassArgument10() (any, error) {

	startCoord, endCoord, err := GetCoordinates(c.pos.line, c.pos.col, c.text)
	if err != nil {
		return nil, DummyError(err)
	}
	return nil, CLASS_ARGUMENT_END_MISSING(*startCoord, *endCoord)
}

func (p *parser) callonClassArgument10() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onClassArgument10()
}

func (c *current) onClassArgument15() (any, error) {

	startCoord, endCoord, err := GetCoordinates(c.pos.line, c.pos.col, c.text)
	if err != nil {
		return nil, DummyError(err)
	}
	return nil, CLASS_ARGUMENT_START_MISSING(*startCoord, *endCoord)
}

func (p *parser) callonClassArgument15() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onClassArgument15()
}

func (c *current) onOptionArgument2(options any) (any, error) {

	argument := newOptionArgument(options.(string))
	return argument, nil

	// Handling if the closing bracket ']' is missing
}

func (p *parser) callonOptionArgument2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOptionArgument2(stack["options"])
}

func (c *current) onOptionArgument10() (any, error) {

	startCoord, endCoord, err := GetCoordinates(c.pos.line, c.pos.col, c.text)
	if err != nil {
		return nil, DummyError(err)
	}
	return nil, OPTIONS_ARGUMENT_END_MISSING(*startCoord, *endCoord)
}

func (p *parser) callonOptionArgument10() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOptionArgument10()
}

func (c *current) onOptionArgument15() (any, error) {

	startCoord, endCoord, err := GetCoordinates(c.pos.line, c.pos.col, c.text)
	if err != nil {
		return nil, DummyError(err)
	}
	return nil, OPTIONS_ARGUMENT_START_MISSING(*startCoord, *endCoord)
}

func (p *parser) callonOptionArgument15() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOptionArgument15()
}

func (c *current) onArgumentContent1() (any, error) {

	return string(c.text), nil
}

func (p *parser) callonArgumentContent1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArgumentContent1()
}

func (c *current) onArgumentOpen1(str any) (any, error) {

	chr := string(str.([]byte))
	argumentStack.Push(chr)
	return chr, nil
}

func (p *parser) callonArgumentOpen1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArgumentOpen1(stack["str"])
}

func (c *current) onArgumentClose3() (bool, error) {

	// only match against the ending if there is a starting component
	// otherwise, we assume it is to be matched by the argument itself rather than its inner contents
	if argumentStack.IsEmpty() {
		return false, nil
	}
	return true, nil
}

func (p *parser) callonArgumentClose3() (bool, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArgumentClose3()
}

func (c *current) onArgumentClose1(str any) (any, error) {

	startCoord, endCoord, err := GetCoordinates(c.pos.line, c.pos.col, c.text)
	if err != nil {
		return nil, DummyError(err)
	}

	argMapping := map[string]string{
		"[": "]",
		"{": "}",
	}

	closeChr := string(str.([]byte))
	openChr, errFn := argumentStack.Pop()
	if errFn != nil {
		return nil, errFn(*startCoord, *endCoord)
	}
	expectedCloseChr, ok := argMapping[openChr]
	if !ok {
		return nil, errors.New("uh oh")
	}
	if expectedCloseChr != closeChr {
		return nil, errors.New("uh oh 2")
	}
	return nil, nil
}

func (p *parser) callonArgumentClose1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArgumentClose1(stack["str"])
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
