{
    package main

    var groupStack Stack
}

/**
  * This section deals with the overall formatting of the document.
  * This includes enforcing an expected format is used, and handling of every component of the document.
  * Additionally, it is necessary to return the overall Document struct created to represent the parsed document.
  */
// Matches against overall document structure
Input <- text prerequisite:PrerequisiteContent text docclass:DocumentClass text preamble:Preamble text content:DocumentContent text EOF {
    var documentBuilder IDocumentBuilder = newDocumentBuilder()

    // handling prerequisite
    if prerequisite != nil {
        for _, component := range prerequisite.([]Component) {
            err := documentBuilder.addPrerequisiteLine(component)
            if err != nil {
                return nil, err
            }
        }
    }

    // handling docclass
    if docclass != nil {
        err := documentBuilder.addDocumentClass(*docclass.(*Line))
        if err != nil {
            return nil, err
        }
    }

    // handling preamble
    if preamble != nil {
        for _, line := range preamble.([]Line) {
            err := documentBuilder.addPreambleLine(line)
            if err != nil {
                return nil, err
            }
        }
    }

    // handling document content
    if content != nil {
        for _, component := range content.([]Component) {
            err := documentBuilder.addDocumentContent(component)
            if err != nil {
                return nil, err
            }
        }
    }

    // additional checks over the document occur during creation
    return documentBuilder.buildDocument()
}

// Handles commands that precede the document class
// These should be rarely used in most LaTeX documents
PrerequisiteContent <- lines:MultiLaTeXLines {
    return lines, nil
}

// Handles the document class i.e. overall categorisation of the LaTeX document
DocumentClass <- command_start name:`documentclass` args:MultiArgument {
    arguments := args.([]Argument)
    return newLine(string(name.([]byte)), arguments), nil
} / t:text {
    return nil, errors.New("Unrecognised document class (may be missing or incorrect)")
}

// Handles metadata (i.e. the head) about the LaTeX document
Preamble <- lines:MultiSimpleLaTeXLines {
    return lines, nil
}

// Handles the overall content (i.e. the body) of the LaTeX document
DocumentContent <- lines:MultiLaTeXLines {
    return lines, nil
}

// Ensures the document does not match any further
// i.e. it ensures the End-of-File has been reached
EOF <- !.

/**
  * This section deals with LaTeX lines that require grouped contexts. 
  * For example, all document content should be grouped under the 'document'.
  */
MultiLaTeXLines <- lines:LaTeXLine* {
    var result []Component
    var stack Stack
    for _, component := range AnyInterfaceToComponentSlice(lines) {
        // Handling ending groups
        if component == nil {
            _, err := stack.Pop()
            if err != nil {
                return nil, err
            }
            continue
        }

        // adding component to pre-existing groups if necessary
        if !stack.IsEmpty() {
            peek, err := stack.Peek()
            if err != nil {
                return nil, err
            }
            peer, ok := peek.(*Group)
            if !ok {
                return nil, errors.New("Stack contains non-group member")
            }
            peer.AddComponent(component)
        
        // add to the result if this is the topmost layer
        } else if component != nil { // nil check is provided for future-proofing, even if it is redundant atm
            result = append(result, component)
        }
        
        // handling grouped contexts
        _, ok := component.(*Group)
        if ok {
            stack.Push(component)
            continue
        }
    }
    return result, nil
}

LaTeXLine <- text line:(BeginGroup / EndGroup / SimpleLaTeXLine) text {
    return line, nil
}

BeginGroup <- command_start `begin` name:ClassArgument args:MultiArgument {
    arguments := args.([]Argument)
    group := newGroup(name.(Argument).GetValue(), arguments)
    groupStack.Push(group)
    return group, nil
}

EndGroup <- command_start `end` name:ClassArgument args:MultiArgument {
    peek, err := groupStack.Pop()
    if err != nil {
        return nil, fmt.Errorf("Missing associated begin (\\end{%s})", name)
    }
    if peek.GetName() != name.(Argument).GetValue() {
        return nil, fmt.Errorf("Most recent \\begin statement did not match the current \\end statement (found \\end{%s}, expected \\end{%s})", name, peek)
    }
    return nil, nil
}

/**
  * This section handles simple LaTeX lines that do not require knowing about the other lines to be processed.
  */
MultiSimpleLaTeXLines <- lines:SimpleWrappedLaTeXLine* {
    return AnyInterfaceToTSlice[Line](lines), nil
}

SimpleWrappedLaTeXLine <- text line:SimpleLaTeXLine text {
    return *line.(*Line), nil
}

// Handles any LaTeX line and provides it a data structure to be parsed further
// disallow 'documentclass', 'begin', and 'end' since they are handled separately
SimpleLaTeXLine <- command_start !`documentclass` !`begin` !`end` name:word+ args:MultiArgument {
    arguments := args.([]Argument)
    line := newLine(AnyInterfaceToString(name), arguments)
    return line, nil
}

/**
  * This section deals with argument handling of individual LaTeX commands.
  * Namely, components within them that are surrounded by curly braces '{}' or square brackets '[]'.
  * This section also includes handling for multiple arguments one after the other.
  */

// Handles zero or more arguments in a row, directly one after the other
MultiArgument <- arguments:Argument* {
    return AnyInterfaceToTSlice[Argument](RemoveNilElements(arguments.([]any))), nil
}

// Handles either possible arguments, ensuring a uniform method of management
Argument <- argument:(OptionArgument / ClassArgument) {
    return argument, nil
}

// For our purposes, a class argument is defined as one surrounded by curly braces '{}'
ClassArgument <- '{' _ class:argument_container _ '}' {
    argument := newClassArgument(AnyInterfaceToString(class))
    return argument, nil

// Handling if the closing brace '}' is missing
} / '{' _ text:non_whitespace+ {
    fmt.Printf("%#v\n", text)
    return nil, fmt.Errorf("Expected an argument wrapped in {}, got %s instead.", AnyInterfaceToString(text))
} / text:argument_container _ '}' {
    fmt.Printf("%#v\n", AnyInterfaceToString(text))
    return nil, fmt.Errorf("Replace with custom error later")
}

// For our purposes, an option argument is defined as one surrounded by square brackets '[]'
OptionArgument <- '[' _ options:argument_container _ ']' {
    argument := newOptionArgument(AnyInterfaceToString(options))
    return argument, nil

// Handling if the closing bracket ']' is missing
} / '[' _ text:non_whitespace+ {
    return nil, fmt.Errorf("Expected an argument wrapped in [], got %s instead.", AnyInterfaceToString(text))
} / text:argument_container _ ']' {
    return nil, fmt.Errorf("Replace with custom error later")
}

/**
  * This section deals with character classes which are used to indicate a group of characters, or the lack thereof.
  * It serves a purpose of improving maintainability and readability of the overall PEG script.
  */
// Handles character class for characters between argument containers
// i.e. the text in '{' text '}' or '[' text ']'
argument_container <- [^\\\]}\n\r]+

// Handles supported commands, currently only including \
command_start <- '\\'
non_special <- [^\\]
text "zero or more non-special characters" <- non_special*

// Handles word characters
word <- [a-zA-Z0-9_]
non_word <- [^a-zA-Z0-9_]

// whitespace handling
non_whitespace <- [^ \n\t\r]
whitespace <- [ \n\t\r]
_ "zero or more whitespace characters" <- whitespace*