// Code generated by pigeon; DO NOT EDIT.

package main

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

var groupStack Stack

var g = &grammar{
	rules: []*rule{
		{
			name: "Input",
			pos:  position{line: 13, col: 1, offset: 402},
			expr: &actionExpr{
				pos: position{line: 13, col: 10, offset: 411},
				run: (*parser).callonInput1,
				expr: &seqExpr{
					pos: position{line: 13, col: 10, offset: 411},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 13, col: 10, offset: 411},
							name: "text",
						},
						&labeledExpr{
							pos:   position{line: 13, col: 15, offset: 416},
							label: "prerequisite",
							expr: &ruleRefExpr{
								pos:  position{line: 13, col: 28, offset: 429},
								name: "PrerequisiteContent",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 13, col: 48, offset: 449},
							name: "text",
						},
						&labeledExpr{
							pos:   position{line: 13, col: 53, offset: 454},
							label: "docclass",
							expr: &ruleRefExpr{
								pos:  position{line: 13, col: 62, offset: 463},
								name: "DocumentClass",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 13, col: 76, offset: 477},
							name: "text",
						},
						&labeledExpr{
							pos:   position{line: 13, col: 81, offset: 482},
							label: "preamble",
							expr: &ruleRefExpr{
								pos:  position{line: 13, col: 90, offset: 491},
								name: "Preamble",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 13, col: 99, offset: 500},
							name: "text",
						},
						&labeledExpr{
							pos:   position{line: 13, col: 104, offset: 505},
							label: "content",
							expr: &ruleRefExpr{
								pos:  position{line: 13, col: 112, offset: 513},
								name: "DocumentContent",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 13, col: 128, offset: 529},
							name: "text",
						},
						&ruleRefExpr{
							pos:  position{line: 13, col: 133, offset: 534},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "PrerequisiteContent",
			pos:  position{line: 60, col: 1, offset: 1852},
			expr: &actionExpr{
				pos: position{line: 60, col: 24, offset: 1875},
				run: (*parser).callonPrerequisiteContent1,
				expr: &labeledExpr{
					pos:   position{line: 60, col: 24, offset: 1875},
					label: "lines",
					expr: &ruleRefExpr{
						pos:  position{line: 60, col: 30, offset: 1881},
						name: "MultiLaTeXLines",
					},
				},
			},
		},
		{
			name: "DocumentClass",
			pos:  position{line: 65, col: 1, offset: 2009},
			expr: &choiceExpr{
				pos: position{line: 65, col: 18, offset: 2026},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 65, col: 18, offset: 2026},
						run: (*parser).callonDocumentClass2,
						expr: &seqExpr{
							pos: position{line: 65, col: 18, offset: 2026},
							exprs: []any{
								&ruleRefExpr{
									pos:  position{line: 65, col: 18, offset: 2026},
									name: "command_start",
								},
								&labeledExpr{
									pos:   position{line: 65, col: 32, offset: 2040},
									label: "name",
									expr: &litMatcher{
										pos:        position{line: 65, col: 37, offset: 2045},
										val:        "documentclass",
										ignoreCase: false,
										want:       "\"documentclass\"",
									},
								},
								&labeledExpr{
									pos:   position{line: 65, col: 53, offset: 2061},
									label: "args",
									expr: &ruleRefExpr{
										pos:  position{line: 65, col: 58, offset: 2066},
										name: "MultiArgument",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 68, col: 5, offset: 2182},
						run: (*parser).callonDocumentClass9,
						expr: &labeledExpr{
							pos:   position{line: 68, col: 5, offset: 2182},
							label: "t",
							expr: &ruleRefExpr{
								pos:  position{line: 68, col: 7, offset: 2184},
								name: "text",
							},
						},
					},
				},
			},
		},
		{
			name: "Preamble",
			pos:  position{line: 73, col: 1, offset: 2348},
			expr: &actionExpr{
				pos: position{line: 73, col: 13, offset: 2360},
				run: (*parser).callonPreamble1,
				expr: &labeledExpr{
					pos:   position{line: 73, col: 13, offset: 2360},
					label: "lines",
					expr: &ruleRefExpr{
						pos:  position{line: 73, col: 19, offset: 2366},
						name: "MultiSimpleLaTeXLines",
					},
				},
			},
		},
		{
			name: "DocumentContent",
			pos:  position{line: 78, col: 1, offset: 2489},
			expr: &actionExpr{
				pos: position{line: 78, col: 20, offset: 2508},
				run: (*parser).callonDocumentContent1,
				expr: &labeledExpr{
					pos:   position{line: 78, col: 20, offset: 2508},
					label: "lines",
					expr: &ruleRefExpr{
						pos:  position{line: 78, col: 26, offset: 2514},
						name: "MultiLaTeXLines",
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 84, col: 1, offset: 2666},
			expr: &notExpr{
				pos: position{line: 84, col: 8, offset: 2673},
				expr: &anyMatcher{
					line: 84, col: 9, offset: 2674,
				},
			},
		},
		{
			name: "MultiLaTeXLines",
			pos:  position{line: 90, col: 1, offset: 2842},
			expr: &actionExpr{
				pos: position{line: 90, col: 20, offset: 2861},
				run: (*parser).callonMultiLaTeXLines1,
				expr: &labeledExpr{
					pos:   position{line: 90, col: 20, offset: 2861},
					label: "lines",
					expr: &zeroOrMoreExpr{
						pos: position{line: 90, col: 26, offset: 2867},
						expr: &ruleRefExpr{
							pos:  position{line: 90, col: 26, offset: 2867},
							name: "LaTeXLine",
						},
					},
				},
			},
		},
		{
			name: "LaTeXLine",
			pos:  position{line: 130, col: 1, offset: 4063},
			expr: &actionExpr{
				pos: position{line: 130, col: 14, offset: 4076},
				run: (*parser).callonLaTeXLine1,
				expr: &seqExpr{
					pos: position{line: 130, col: 14, offset: 4076},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 130, col: 14, offset: 4076},
							name: "text",
						},
						&labeledExpr{
							pos:   position{line: 130, col: 19, offset: 4081},
							label: "line",
							expr: &choiceExpr{
								pos: position{line: 130, col: 25, offset: 4087},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 130, col: 25, offset: 4087},
										name: "BeginGroup",
									},
									&ruleRefExpr{
										pos:  position{line: 130, col: 38, offset: 4100},
										name: "EndGroup",
									},
									&ruleRefExpr{
										pos:  position{line: 130, col: 49, offset: 4111},
										name: "SimpleLaTeXLine",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 130, col: 66, offset: 4128},
							name: "text",
						},
					},
				},
			},
		},
		{
			name: "BeginGroup",
			pos:  position{line: 134, col: 1, offset: 4163},
			expr: &actionExpr{
				pos: position{line: 134, col: 15, offset: 4177},
				run: (*parser).callonBeginGroup1,
				expr: &seqExpr{
					pos: position{line: 134, col: 15, offset: 4177},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 134, col: 15, offset: 4177},
							name: "command_start",
						},
						&litMatcher{
							pos:        position{line: 134, col: 29, offset: 4191},
							val:        "begin",
							ignoreCase: false,
							want:       "\"begin\"",
						},
						&labeledExpr{
							pos:   position{line: 134, col: 37, offset: 4199},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 134, col: 42, offset: 4204},
								name: "ClassArgument",
							},
						},
						&labeledExpr{
							pos:   position{line: 134, col: 56, offset: 4218},
							label: "args",
							expr: &ruleRefExpr{
								pos:  position{line: 134, col: 61, offset: 4223},
								name: "MultiArgument",
							},
						},
					},
				},
			},
		},
		{
			name: "EndGroup",
			pos:  position{line: 141, col: 1, offset: 4394},
			expr: &actionExpr{
				pos: position{line: 141, col: 13, offset: 4406},
				run: (*parser).callonEndGroup1,
				expr: &seqExpr{
					pos: position{line: 141, col: 13, offset: 4406},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 141, col: 13, offset: 4406},
							name: "command_start",
						},
						&litMatcher{
							pos:        position{line: 141, col: 27, offset: 4420},
							val:        "end",
							ignoreCase: false,
							want:       "\"end\"",
						},
						&labeledExpr{
							pos:   position{line: 141, col: 33, offset: 4426},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 141, col: 38, offset: 4431},
								name: "ClassArgument",
							},
						},
						&labeledExpr{
							pos:   position{line: 141, col: 52, offset: 4445},
							label: "args",
							expr: &ruleRefExpr{
								pos:  position{line: 141, col: 57, offset: 4450},
								name: "MultiArgument",
							},
						},
					},
				},
			},
		},
		{
			name: "MultiSimpleLaTeXLines",
			pos:  position{line: 155, col: 1, offset: 4976},
			expr: &actionExpr{
				pos: position{line: 155, col: 26, offset: 5001},
				run: (*parser).callonMultiSimpleLaTeXLines1,
				expr: &labeledExpr{
					pos:   position{line: 155, col: 26, offset: 5001},
					label: "lines",
					expr: &zeroOrMoreExpr{
						pos: position{line: 155, col: 32, offset: 5007},
						expr: &ruleRefExpr{
							pos:  position{line: 155, col: 32, offset: 5007},
							name: "SimpleWrappedLaTeXLine",
						},
					},
				},
			},
		},
		{
			name: "SimpleWrappedLaTeXLine",
			pos:  position{line: 159, col: 1, offset: 5090},
			expr: &actionExpr{
				pos: position{line: 159, col: 27, offset: 5116},
				run: (*parser).callonSimpleWrappedLaTeXLine1,
				expr: &seqExpr{
					pos: position{line: 159, col: 27, offset: 5116},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 159, col: 27, offset: 5116},
							name: "text",
						},
						&labeledExpr{
							pos:   position{line: 159, col: 32, offset: 5121},
							label: "line",
							expr: &ruleRefExpr{
								pos:  position{line: 159, col: 37, offset: 5126},
								name: "SimpleLaTeXLine",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 159, col: 53, offset: 5142},
							name: "text",
						},
					},
				},
			},
		},
		{
			name: "SimpleLaTeXLine",
			pos:  position{line: 165, col: 1, offset: 5350},
			expr: &actionExpr{
				pos: position{line: 165, col: 20, offset: 5369},
				run: (*parser).callonSimpleLaTeXLine1,
				expr: &seqExpr{
					pos: position{line: 165, col: 20, offset: 5369},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 165, col: 20, offset: 5369},
							name: "command_start",
						},
						&notExpr{
							pos: position{line: 165, col: 34, offset: 5383},
							expr: &litMatcher{
								pos:        position{line: 165, col: 35, offset: 5384},
								val:        "documentclass",
								ignoreCase: false,
								want:       "\"documentclass\"",
							},
						},
						&notExpr{
							pos: position{line: 165, col: 51, offset: 5400},
							expr: &litMatcher{
								pos:        position{line: 165, col: 52, offset: 5401},
								val:        "begin",
								ignoreCase: false,
								want:       "\"begin\"",
							},
						},
						&notExpr{
							pos: position{line: 165, col: 60, offset: 5409},
							expr: &litMatcher{
								pos:        position{line: 165, col: 61, offset: 5410},
								val:        "end",
								ignoreCase: false,
								want:       "\"end\"",
							},
						},
						&labeledExpr{
							pos:   position{line: 165, col: 67, offset: 5416},
							label: "name",
							expr: &oneOrMoreExpr{
								pos: position{line: 165, col: 72, offset: 5421},
								expr: &ruleRefExpr{
									pos:  position{line: 165, col: 72, offset: 5421},
									name: "word",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 165, col: 78, offset: 5427},
							label: "args",
							expr: &ruleRefExpr{
								pos:  position{line: 165, col: 83, offset: 5432},
								name: "MultiArgument",
							},
						},
					},
				},
			},
		},
		{
			name: "MultiArgument",
			pos:  position{line: 178, col: 1, offset: 5923},
			expr: &actionExpr{
				pos: position{line: 178, col: 18, offset: 5940},
				run: (*parser).callonMultiArgument1,
				expr: &labeledExpr{
					pos:   position{line: 178, col: 18, offset: 5940},
					label: "arguments",
					expr: &zeroOrMoreExpr{
						pos: position{line: 178, col: 28, offset: 5950},
						expr: &ruleRefExpr{
							pos:  position{line: 178, col: 28, offset: 5950},
							name: "Argument",
						},
					},
				},
			},
		},
		{
			name: "Argument",
			pos:  position{line: 183, col: 1, offset: 6133},
			expr: &actionExpr{
				pos: position{line: 183, col: 13, offset: 6145},
				run: (*parser).callonArgument1,
				expr: &labeledExpr{
					pos:   position{line: 183, col: 13, offset: 6145},
					label: "argument",
					expr: &choiceExpr{
						pos: position{line: 183, col: 23, offset: 6155},
						alternatives: []any{
							&ruleRefExpr{
								pos:  position{line: 183, col: 23, offset: 6155},
								name: "OptionArgument",
							},
							&ruleRefExpr{
								pos:  position{line: 183, col: 40, offset: 6172},
								name: "ClassArgument",
							},
						},
					},
				},
			},
		},
		{
			name: "ClassArgument",
			pos:  position{line: 188, col: 1, offset: 6310},
			expr: &choiceExpr{
				pos: position{line: 188, col: 18, offset: 6327},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 188, col: 18, offset: 6327},
						run: (*parser).callonClassArgument2,
						expr: &seqExpr{
							pos: position{line: 188, col: 18, offset: 6327},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 188, col: 18, offset: 6327},
									val:        "{",
									ignoreCase: false,
									want:       "\"{\"",
								},
								&ruleRefExpr{
									pos:  position{line: 188, col: 22, offset: 6331},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 188, col: 24, offset: 6333},
									label: "class",
									expr: &ruleRefExpr{
										pos:  position{line: 188, col: 30, offset: 6339},
										name: "argument_container",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 188, col: 49, offset: 6358},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 188, col: 51, offset: 6360},
									val:        "}",
									ignoreCase: false,
									want:       "\"}\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 193, col: 5, offset: 6511},
						run: (*parser).callonClassArgument10,
						expr: &seqExpr{
							pos: position{line: 193, col: 5, offset: 6511},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 193, col: 5, offset: 6511},
									val:        "{",
									ignoreCase: false,
									want:       "\"{\"",
								},
								&ruleRefExpr{
									pos:  position{line: 193, col: 9, offset: 6515},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 193, col: 11, offset: 6517},
									label: "text",
									expr: &oneOrMoreExpr{
										pos: position{line: 193, col: 16, offset: 6522},
										expr: &ruleRefExpr{
											pos:  position{line: 193, col: 16, offset: 6522},
											name: "non_whitespace",
										},
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 196, col: 5, offset: 6687},
						run: (*parser).callonClassArgument17,
						expr: &seqExpr{
							pos: position{line: 196, col: 5, offset: 6687},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 196, col: 5, offset: 6687},
									label: "text",
									expr: &ruleRefExpr{
										pos:  position{line: 196, col: 10, offset: 6692},
										name: "argument_container",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 196, col: 29, offset: 6711},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 196, col: 31, offset: 6713},
									val:        "}",
									ignoreCase: false,
									want:       "\"}\"",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "OptionArgument",
			pos:  position{line: 202, col: 1, offset: 6935},
			expr: &choiceExpr{
				pos: position{line: 202, col: 19, offset: 6953},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 202, col: 19, offset: 6953},
						run: (*parser).callonOptionArgument2,
						expr: &seqExpr{
							pos: position{line: 202, col: 19, offset: 6953},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 202, col: 19, offset: 6953},
									val:        "[",
									ignoreCase: false,
									want:       "\"[\"",
								},
								&ruleRefExpr{
									pos:  position{line: 202, col: 23, offset: 6957},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 202, col: 25, offset: 6959},
									label: "options",
									expr: &ruleRefExpr{
										pos:  position{line: 202, col: 33, offset: 6967},
										name: "argument_container",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 202, col: 52, offset: 6986},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 202, col: 54, offset: 6988},
									val:        "]",
									ignoreCase: false,
									want:       "\"]\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 207, col: 5, offset: 7144},
						run: (*parser).callonOptionArgument10,
						expr: &seqExpr{
							pos: position{line: 207, col: 5, offset: 7144},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 207, col: 5, offset: 7144},
									val:        "[",
									ignoreCase: false,
									want:       "\"[\"",
								},
								&ruleRefExpr{
									pos:  position{line: 207, col: 9, offset: 7148},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 207, col: 11, offset: 7150},
									label: "text",
									expr: &oneOrMoreExpr{
										pos: position{line: 207, col: 16, offset: 7155},
										expr: &ruleRefExpr{
											pos:  position{line: 207, col: 16, offset: 7155},
											name: "non_whitespace",
										},
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 209, col: 5, offset: 7289},
						run: (*parser).callonOptionArgument17,
						expr: &seqExpr{
							pos: position{line: 209, col: 5, offset: 7289},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 209, col: 5, offset: 7289},
									label: "text",
									expr: &ruleRefExpr{
										pos:  position{line: 209, col: 10, offset: 7294},
										name: "argument_container",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 209, col: 29, offset: 7313},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 209, col: 31, offset: 7315},
									val:        "]",
									ignoreCase: false,
									want:       "\"]\"",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "argument_container",
			pos:  position{line: 219, col: 1, offset: 7737},
			expr: &oneOrMoreExpr{
				pos: position{line: 219, col: 23, offset: 7759},
				expr: &charClassMatcher{
					pos:        position{line: 219, col: 23, offset: 7759},
					val:        "[^\\\\\\]}\\n\\r]",
					chars:      []rune{'\\', ']', '}', '\n', '\r'},
					ignoreCase: false,
					inverted:   true,
				},
			},
		},
		{
			name: "command_start",
			pos:  position{line: 222, col: 1, offset: 7835},
			expr: &litMatcher{
				pos:        position{line: 222, col: 18, offset: 7852},
				val:        "\\",
				ignoreCase: false,
				want:       "\"\\\\\"",
			},
		},
		{
			name: "non_special",
			pos:  position{line: 223, col: 1, offset: 7858},
			expr: &charClassMatcher{
				pos:        position{line: 223, col: 16, offset: 7873},
				val:        "[^\\\\]",
				chars:      []rune{'\\'},
				ignoreCase: false,
				inverted:   true,
			},
		},
		{
			name:        "text",
			displayName: "\"zero or more non-special characters\"",
			pos:         position{line: 224, col: 1, offset: 7880},
			expr: &zeroOrMoreExpr{
				pos: position{line: 224, col: 47, offset: 7926},
				expr: &ruleRefExpr{
					pos:  position{line: 224, col: 47, offset: 7926},
					name: "non_special",
				},
			},
		},
		{
			name: "word",
			pos:  position{line: 227, col: 1, offset: 7970},
			expr: &charClassMatcher{
				pos:        position{line: 227, col: 9, offset: 7978},
				val:        "[a-zA-Z0-9_]",
				chars:      []rune{'_'},
				ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "non_word",
			pos:  position{line: 228, col: 1, offset: 7992},
			expr: &charClassMatcher{
				pos:        position{line: 228, col: 13, offset: 8004},
				val:        "[^a-zA-Z0-9_]",
				chars:      []rune{'_'},
				ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
				ignoreCase: false,
				inverted:   true,
			},
		},
		{
			name: "non_whitespace",
			pos:  position{line: 231, col: 1, offset: 8045},
			expr: &charClassMatcher{
				pos:        position{line: 231, col: 19, offset: 8063},
				val:        "[^ \\n\\t\\r]",
				chars:      []rune{' ', '\n', '\t', '\r'},
				ignoreCase: false,
				inverted:   true,
			},
		},
		{
			name: "whitespace",
			pos:  position{line: 232, col: 1, offset: 8075},
			expr: &charClassMatcher{
				pos:        position{line: 232, col: 15, offset: 8089},
				val:        "[ \\n\\t\\r]",
				chars:      []rune{' ', '\n', '\t', '\r'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name:        "_",
			displayName: "\"zero or more whitespace characters\"",
			pos:         position{line: 233, col: 1, offset: 8100},
			expr: &zeroOrMoreExpr{
				pos: position{line: 233, col: 43, offset: 8142},
				expr: &ruleRefExpr{
					pos:  position{line: 233, col: 43, offset: 8142},
					name: "whitespace",
				},
			},
		},
	},
}

func (c *current) onInput1(prerequisite, docclass, preamble, content any) (any, error) {

	var documentBuilder IDocumentBuilder = newDocumentBuilder()

	// handling prerequisite
	if prerequisite != nil {
		for _, component := range prerequisite.([]Component) {
			err := documentBuilder.addPrerequisiteLine(component)
			if err != nil {
				return nil, err
			}
		}
	}

	// handling docclass
	if docclass != nil {
		err := documentBuilder.addDocumentClass(*docclass.(*Line))
		if err != nil {
			return nil, err
		}
	}

	// handling preamble
	if preamble != nil {
		for _, line := range preamble.([]Line) {
			err := documentBuilder.addPreambleLine(line)
			if err != nil {
				return nil, err
			}
		}
	}

	// handling document content
	if content != nil {
		for _, component := range content.([]Component) {
			err := documentBuilder.addDocumentContent(component)
			if err != nil {
				return nil, err
			}
		}
	}

	// additional checks over the document occur during creation
	return documentBuilder.buildDocument()
}

func (p *parser) callonInput1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInput1(stack["prerequisite"], stack["docclass"], stack["preamble"], stack["content"])
}

func (c *current) onPrerequisiteContent1(lines any) (any, error) {

	return lines, nil
}

func (p *parser) callonPrerequisiteContent1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPrerequisiteContent1(stack["lines"])
}

func (c *current) onDocumentClass2(name, args any) (any, error) {

	arguments := args.([]Argument)
	return newLine(string(name.([]byte)), arguments), nil
}

func (p *parser) callonDocumentClass2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDocumentClass2(stack["name"], stack["args"])
}

func (c *current) onDocumentClass9(t any) (any, error) {

	return nil, errors.New("Unrecognised document class (may be missing or incorrect)")
}

func (p *parser) callonDocumentClass9() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDocumentClass9(stack["t"])
}

func (c *current) onPreamble1(lines any) (any, error) {

	return lines, nil
}

func (p *parser) callonPreamble1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPreamble1(stack["lines"])
}

func (c *current) onDocumentContent1(lines any) (any, error) {

	return lines, nil
}

func (p *parser) callonDocumentContent1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDocumentContent1(stack["lines"])
}

func (c *current) onMultiLaTeXLines1(lines any) (any, error) {

	var result []Component
	var stack Stack
	for _, component := range AnyInterfaceToComponentSlice(lines) {
		// Handling ending groups
		if component == nil {
			_, err := stack.Pop()
			if err != nil {
				return nil, err
			}
			continue
		}

		// adding component to pre-existing groups if necessary
		if !stack.IsEmpty() {
			peek, err := stack.Peek()
			if err != nil {
				return nil, err
			}
			peer, ok := peek.(*Group)
			if !ok {
				return nil, errors.New("Stack contains non-group member")
			}
			peer.AddComponent(component)

			// add to the result if this is the topmost layer
		} else if component != nil { // nil check is provided for future-proofing, even if it is redundant atm
			result = append(result, component)
		}

		// handling grouped contexts
		_, ok := component.(*Group)
		if ok {
			stack.Push(component)
			continue
		}
	}
	return result, nil
}

func (p *parser) callonMultiLaTeXLines1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMultiLaTeXLines1(stack["lines"])
}

func (c *current) onLaTeXLine1(line any) (any, error) {

	return line, nil
}

func (p *parser) callonLaTeXLine1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLaTeXLine1(stack["line"])
}

func (c *current) onBeginGroup1(name, args any) (any, error) {

	arguments := args.([]Argument)
	group := newGroup(name.(Argument).GetValue(), arguments)
	groupStack.Push(group)
	return group, nil
}

func (p *parser) callonBeginGroup1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBeginGroup1(stack["name"], stack["args"])
}

func (c *current) onEndGroup1(name, args any) (any, error) {

	peek, err := groupStack.Pop()
	if err != nil {
		return nil, fmt.Errorf("Missing associated begin (\\end{%s})", name)
	}
	if peek.GetName() != name.(Argument).GetValue() {
		return nil, fmt.Errorf("Most recent \\begin statement did not match the current \\end statement (found \\end{%s}, expected \\end{%s})", name, peek)
	}
	return nil, nil
}

func (p *parser) callonEndGroup1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEndGroup1(stack["name"], stack["args"])
}

func (c *current) onMultiSimpleLaTeXLines1(lines any) (any, error) {

	return AnyInterfaceToTSlice[Line](lines), nil
}

func (p *parser) callonMultiSimpleLaTeXLines1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMultiSimpleLaTeXLines1(stack["lines"])
}

func (c *current) onSimpleWrappedLaTeXLine1(line any) (any, error) {

	return *line.(*Line), nil
}

func (p *parser) callonSimpleWrappedLaTeXLine1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSimpleWrappedLaTeXLine1(stack["line"])
}

func (c *current) onSimpleLaTeXLine1(name, args any) (any, error) {

	arguments := args.([]Argument)
	line := newLine(AnyInterfaceToString(name), arguments)
	return line, nil
}

func (p *parser) callonSimpleLaTeXLine1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSimpleLaTeXLine1(stack["name"], stack["args"])
}

func (c *current) onMultiArgument1(arguments any) (any, error) {

	return AnyInterfaceToTSlice[Argument](RemoveNilElements(arguments.([]any))), nil
}

func (p *parser) callonMultiArgument1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMultiArgument1(stack["arguments"])
}

func (c *current) onArgument1(argument any) (any, error) {

	return argument, nil
}

func (p *parser) callonArgument1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArgument1(stack["argument"])
}

func (c *current) onClassArgument2(class any) (any, error) {

	argument := newClassArgument(AnyInterfaceToString(class))
	return argument, nil

	// Handling if the closing brace '}' is missing
}

func (p *parser) callonClassArgument2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onClassArgument2(stack["class"])
}

func (c *current) onClassArgument10(text any) (any, error) {

	fmt.Printf("%#v\n", text)
	return nil, fmt.Errorf("Expected an argument wrapped in {}, got %s instead.", AnyInterfaceToString(text))
}

func (p *parser) callonClassArgument10() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onClassArgument10(stack["text"])
}

func (c *current) onClassArgument17(text any) (any, error) {

	fmt.Printf("%#v\n", AnyInterfaceToString(text))
	return nil, fmt.Errorf("Replace with custom error later")
}

func (p *parser) callonClassArgument17() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onClassArgument17(stack["text"])
}

func (c *current) onOptionArgument2(options any) (any, error) {

	argument := newOptionArgument(AnyInterfaceToString(options))
	return argument, nil

	// Handling if the closing bracket ']' is missing
}

func (p *parser) callonOptionArgument2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOptionArgument2(stack["options"])
}

func (c *current) onOptionArgument10(text any) (any, error) {

	return nil, fmt.Errorf("Expected an argument wrapped in [], got %s instead.", AnyInterfaceToString(text))
}

func (p *parser) callonOptionArgument10() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOptionArgument10(stack["text"])
}

func (c *current) onOptionArgument17(text any) (any, error) {

	return nil, fmt.Errorf("Replace with custom error later")
}

func (p *parser) callonOptionArgument17() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOptionArgument17(stack["text"])
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
